// Objective-C API for talking to github.com/sagernet/sing-box/mobile Go package.
//   gobind -lang=objc github.com/sagernet/sing-box/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileExternalTunAdapter;
@protocol MobilePacketFlow;
@class MobilePacketFlow;

@protocol MobilePacketFlow <NSObject>
- (void)writePacket:(NSData* _Nullable)packet;
@end

@interface MobileExternalTunAdapter : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped method ExternalTunAdapter.Address with unsupported parameter or return types

- (BOOL)close:(NSError* _Nullable* _Nullable)error;
- (long)mtu;
- (NSString* _Nonnull)name;
- (BOOL)read:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
- (BOOL)write:(NSData* _Nullable)p0 n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT NSString* _Nonnull MobileGetLastError(void);

FOUNDATION_EXPORT NSString* _Nonnull MobileGetSingBoxVersion(void);

FOUNDATION_EXPORT long MobileStart(NSString* _Nullable configJSON, NSString* _Nullable workingPath);

FOUNDATION_EXPORT void MobileStartGC(void);

FOUNDATION_EXPORT void MobileStop(void);

FOUNDATION_EXPORT void MobileWriteToGo(NSData* _Nullable packet);

@class MobilePacketFlow;

@interface MobilePacketFlow : NSObject <goSeqRefInterface, MobilePacketFlow> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)writePacket:(NSData* _Nullable)packet;
@end

#endif
