
// Objective-C API for talking to the following Go packages
//
//	github.com/sagernet/sing-box/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __SingBox_FRAMEWORK_H__
#define __SingBox_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
